### ISSUE TITLE
small error in README

### ISSUE THREAD

**Issue by pescobar** [stackhpc/a-universe-from-nothing#106]
README provides these instructions to list the machines registered in the `bifrost_deploy` container in the seed

```
ssh centos@192.168.33.5
sudo docker exec -it bifrost_deploy bash
source env-vars
openstack baremetal node list
```

But file `env-vars` doesn't exist in my test environment. I had to do `source /root/openrc`

```
ssh centos@192.168.33.5
sudo docker exec -it bifrost_deploy bash
source /root/openrc
openstack baremetal node list
```

**Comment by priteau** [comment]
Thanks Pabol. See https://docs.openstack.org/bifrost/latest/user/howto.html for the proper way of accessing bifrost. I have a pull request in review to update our README.
