### ISSUE TITLE
No external network access from kolla container builds

### ISSUE THREAD

**Issue by oneswig** [stackhpc/a-universe-from-nothing#59]
The Seed VM Docker daemon is configured with iptables disabled.  This appears to be an unintended effect of this commit:

https://github.com/stackhpc/a-universe-from-nothing/commit/af360c2b0b7a1342e1f9841ec3ef7c269f32a235

Various options:
- Set the variable `docker_disable_default_iptables_rules` to be true using inventory variables, in `etc/kayobe/kolla/inventory/group_vars` - this may only apply to overcloud
- Configure host network namespace for container builds with config of this form:
```
kolla_build_extra_config: |
  [DEFAULT]
  network_mode = host
```

**Comment by markgoddard** [comment]
We could try this one as a way to disable bridge networking: https://review.opendev.org/#/c/689870
